### ISSUE TITLE
TypeError: unsupported format string passed to Variable.__format__

### ISSUE THREAD

**Issue by zyyhl** [bnulihaixia/Deep_metric#25]
Traceback (most recent call last):
  File "train.py", line 207, in <module>
    main(parser.parse_args())
  File "train.py", line 121, in main
    optimizer=optimizer, train_loader=train_loader, args=args)
  File "/home/user/2T-G/zyy/Deep_metric-master/trainer.py", line 62, in train
    loss=losses, accuracy=accuracy, pos=pos_sims, neg=neg_sims))
TypeError: unsupported format string passed to Variable.__format__
I have encountered the above problem, can you help me solve it? Thanks

**Comment by bnulihaixia** [comment]
which version of pytorch do you use?

**Comment by zyyhl** [comment]
my version of pytorch is 0.2

**Comment by bnulihaixia** [comment]
The code have already  update to pytorch 1.0, you may first try to update your pytorch to 1.0 version, and then to find whether the problem still exists.
